-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.articles
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    country_id integer,
    chapter_id integer,
    "number" integer,
    title character varying,
    article character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.chapters
(
    id integer NOT NULL,
    country_id integer NOT NULL,
    "number" integer,
    title character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.countries
(
    id integer NOT NULL,
    name character varying NOT NULL,
    region_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.preambles
(
    id integer NOT NULL,
    preamble character varying,
    country_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.regions
(
    id integer NOT NULL,
    name character varying(100),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.sections
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    country_id integer,
    chapter_id integer,
    article_id integer,
    "number" integer,
    section character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.subsections
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    country_id integer,
    chapter_id integer,
    article_id integer,
    section_id integer,
    "number" integer,
    subsection character varying,
    PRIMARY KEY (id)
);

ALTER TABLE public.articles
    ADD FOREIGN KEY (country_id)
    REFERENCES public.countries (id)
    NOT VALID;


ALTER TABLE public.articles
    ADD FOREIGN KEY (chapter_id)
    REFERENCES public.chapters (id)
    NOT VALID;


ALTER TABLE public.chapters
    ADD FOREIGN KEY (country_id)
    REFERENCES public.countries (id)
    NOT VALID;


ALTER TABLE public.countries
    ADD FOREIGN KEY (region_id)
    REFERENCES public.regions (id)
    NOT VALID;


ALTER TABLE public.preambles
    ADD FOREIGN KEY (country_id)
    REFERENCES public.countries (id)
    NOT VALID;


ALTER TABLE public.sections
    ADD FOREIGN KEY (country_id)
    REFERENCES public.countries (id)
    NOT VALID;


ALTER TABLE public.sections
    ADD FOREIGN KEY (chapter_id)
    REFERENCES public.chapters (id)
    NOT VALID;


ALTER TABLE public.sections
    ADD FOREIGN KEY (article_id)
    REFERENCES public.articles (id)
    NOT VALID;


ALTER TABLE public.subsections
    ADD FOREIGN KEY (country_id)
    REFERENCES public.countries (id)
    NOT VALID;


ALTER TABLE public.subsections
    ADD FOREIGN KEY (chapter_id)
    REFERENCES public.chapters (id)
    NOT VALID;


ALTER TABLE public.subsections
    ADD FOREIGN KEY (article_id)
    REFERENCES public.articles (id)
    NOT VALID;


ALTER TABLE public.subsections
    ADD FOREIGN KEY (section_id)
    REFERENCES public.sections (id)
    NOT VALID;

END;